# Generated by Django 3.2.8 on 2022-04-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_karen', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karenpost',
            name='image',
        ),
    ]
